package com.example.spendwise.ui.theme

import androidx.compose.ui.graphics.Color

// Brand palette — Financial / Personal Finance
val SpendwiseGreen = Color(0xFF16A34A)
val SpendwiseGreenContainer = Color(0xFFDCFCE7)
val SpendwiseTeal = Color(0xFF0D9488)
val SpendwiseRed = Color(0xFFDC2626)

// Income/Expense semantic colors
val IncomeGreen = Color(0xFF22C55E)
val IncomeGreenDark = Color(0xFF15803D)
val ExpenseRed = Color(0xFFEF4444)
val TransferBlue = Color(0xFF3B82F6)

// Light theme
val md_theme_light_primary = Color(0xFF006B5E)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFF74F8E5)
val md_theme_light_onPrimaryContainer = Color(0xFF00201B)
val md_theme_light_secondary = Color(0xFF4A635F)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFCCE8E2)
val md_theme_light_onSecondaryContainer = Color(0xFF05201C)
val md_theme_light_tertiary = Color(0xFF436278)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFC7E7FF)
val md_theme_light_onTertiaryContainer = Color(0xFF001E2E)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFAFDFB)
val md_theme_light_onBackground = Color(0xFF191C1B)
val md_theme_light_surface = Color(0xFFFAFDFB)
val md_theme_light_onSurface = Color(0xFF191C1B)
val md_theme_light_surfaceVariant = Color(0xFFDAE5E1)
val md_theme_light_onSurfaceVariant = Color(0xFF3F4946)
val md_theme_light_outline = Color(0xFF6F7976)
val md_theme_light_outlineVariant = Color(0xFFBEC9C5)
val md_theme_light_scrim = Color(0xFF000000)
val md_theme_light_inverseSurface = Color(0xFF2D3130)
val md_theme_light_inverseOnSurface = Color(0xFFEFF1EF)
val md_theme_light_inversePrimary = Color(0xFF52DBC9)
val md_theme_light_surfaceContainer = Color(0xFFEDF0EE)
val md_theme_light_surfaceContainerHigh = Color(0xFFE7EAE8)
val md_theme_light_surfaceContainerHighest = Color(0xFFE1E4E2)

// Dark theme
val md_theme_dark_primary = Color(0xFF52DBC9)
val md_theme_dark_onPrimary = Color(0xFF003731)
val md_theme_dark_primaryContainer = Color(0xFF005047)
val md_theme_dark_onPrimaryContainer = Color(0xFF74F8E5)
val md_theme_dark_secondary = Color(0xFFB1CCC7)
val md_theme_dark_onSecondary = Color(0xFF1C3531)
val md_theme_dark_secondaryContainer = Color(0xFF324B47)
val md_theme_dark_onSecondaryContainer = Color(0xFFCCE8E2)
val md_theme_dark_tertiary = Color(0xFFACCBE4)
val md_theme_dark_onTertiary = Color(0xFF133347)
val md_theme_dark_tertiaryContainer = Color(0xFF2A4A5F)
val md_theme_dark_onTertiaryContainer = Color(0xFFC7E7FF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF101413)
val md_theme_dark_onBackground = Color(0xFFE1E4E2)
val md_theme_dark_surface = Color(0xFF101413)
val md_theme_dark_onSurface = Color(0xFFE1E4E2)
val md_theme_dark_surfaceVariant = Color(0xFF3F4946)
val md_theme_dark_onSurfaceVariant = Color(0xFFBEC9C5)
val md_theme_dark_outline = Color(0xFF89938F)
val md_theme_dark_outlineVariant = Color(0xFF3F4946)
val md_theme_dark_scrim = Color(0xFF000000)
val md_theme_dark_inverseSurface = Color(0xFFE1E4E2)
val md_theme_dark_inverseOnSurface = Color(0xFF2D3130)
val md_theme_dark_inversePrimary = Color(0xFF006B5E)
val md_theme_dark_surfaceContainer = Color(0xFF1D201F)
val md_theme_dark_surfaceContainerHigh = Color(0xFF272A29)
val md_theme_dark_surfaceContainerHighest = Color(0xFF323534)